- nri-prelude/src/Log.hs
add a new type instead of using less expressive Boolean.
> avoid boolean when we can use a more expressive name

- nri-log-explorer/src/Main.hs
- nri-log-explorer/src/Zipper.hs
You can run this version by running `cabal run log-explorer` on the branch!
> Log explorer fixes

- nix/sources.json
- nri-prelude/package.yaml
- nri-prelude/src/Expect.hs
- shell.nix
> Update pretty diff

- nri-prelude/src/Expect.hs
- nri-prelude/src/Expect/Task.hs
- nri-prelude/src/Test/Internal.hs
- nri-prelude/src/Test/Reporter/Junit.hs
- nri-prelude/src/Test/Reporter/Stdout.hs
- nri-prelude/tests/Main.hs
- nri-prelude/tests/TestSpec.hs
- nri-prelude/tests/golden-results/test-report-logfile-all-passed
- nri-prelude/tests/golden-results/test-report-logfile-no-tests-in-suite
- nri-prelude/tests/golden-results/test-report-logfile-onlys-passed
- nri-prelude/tests/golden-results/test-report-logfile-passed-with-skipped
- nri-prelude/tests/golden-results/test-report-logfile-tests-failed
- nri-prelude/tests/golden-results/test-report-stdout-tests-failed-loc
> Print location of failing expectation

- nri-prelude/src/Expect.hs
- nri-prelude/tests/TestSpec.hs
- nri-prelude/tests/golden-results/test-report-logfile-all-passed
- nri-prelude/tests/golden-results/test-report-logfile-no-tests-in-suite
- nri-prelude/tests/golden-results/test-report-logfile-onlys-passed
- nri-prelude/tests/golden-results/test-report-logfile-passed-with-skipped
- nri-prelude/tests/golden-results/test-report-logfile-tests-failed
- nri-prelude/tests/golden-results/test-report-stdout-tests-failed-loc
Small bit of follow-up to #41.
> Float expectations

- nix/mk-shell.nix
- nri-log-explorer/package.yaml
- nri-log-explorer/src/Main.hs
> Filter root spans

- .gitignore
- nri-env-parser/nri-env-parser.cabal
- nri-env-parser/package.yaml
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-observability/nri-observability.cabal
- nri-observability/package.yaml
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
- test.sh
resolves some of #50 
see: https://www.fpcomplete.com/blog/storing-generated-cabal-files/
this PR
1. adds cabal files
2. ensures adding cabal files in CI
> Commit cabal files

- nri-env-parser/CHANGELOG.md
- nri-env-parser/nri-env-parser.cabal
- nri-env-parser/package.yaml
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-observability/nri-observability.cabal
- nri-observability/package.yaml
- nri-prelude/CHANGELOG.md
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
- nri-prelude/src/Array.hs
- release.sh
bumps all of our packages and makes some small changes to the release script
paired with @jwoudenberg and @stoeffel
> Prep for misc library releases

- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/src/Filterable.hs
- nri-log-explorer/src/Main.hs
- nri-log-explorer/src/Modifiable.hs
Small refactor to make modifying a ListWidget.List simpler.
I thought that it would still be nicer to not make `Modifiable.ListWidget` to bloated by also adding `data Filter`.
> Refactoring filtering

- nri-log-explorer/src/Main.hs
adds life search and navigating to previous match using `N`.
> Search enhancements

- nix/mk-shell.nix
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-log-explorer/src/Main.hs
> Caseless search

- nix/sources.json
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/src/Main.hs
> New show failed

- Makefile
- nri-prelude/src/Debug.hs
- nri-prelude/tests/TestSpec.hs
- nri-prelude/tests/golden-results/debug-todo-stacktrace
- nri-prelude/tests/golden-results/test-report-logfile-all-passed
- nri-prelude/tests/golden-results/test-report-logfile-no-tests-in-suite
- nri-prelude/tests/golden-results/test-report-logfile-onlys-passed
- nri-prelude/tests/golden-results/test-report-logfile-passed-with-skipped
- nri-prelude/tests/golden-results/test-report-logfile-tests-failed
- nri-prelude/tests/golden-results/test-report-stdout-tests-failed-loc
> Debug.todo returns a more useful stack trace

- nri-log-explorer/CHANGELOG.md
- nri-log-explorer/nri-log-explorer.cabal
- nri-prelude/CHANGELOG.md
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
- release.sh
updates changelogs and versions for nri-log-explorer and nri-prelude
> bump versions

- Makefile
- nri-log-explorer/CHANGELOG.md
- nri-log-explorer/src/Main.hs
> Log explorer search improvements

- nri-env-parser/CHANGELOG.md
- nri-env-parser/nri-env-parser.cabal
- nri-env-parser/package.yaml
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-observability/CHANGELOG.md
- nri-observability/nri-observability.cabal
- nri-observability/package.yaml
- nri-prelude/CHANGELOG.md
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
> Support base-1.15

- nri-env-parser/CHANGELOG.md
- nri-env-parser/nri-env-parser.cabal
- nri-env-parser/package.yaml
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-observability/CHANGELOG.md
- nri-observability/nri-observability.cabal
- nri-observability/package.yaml
- nri-prelude/CHANGELOG.md
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
release 0.6.0.0 because 0.5.0.3 includes a breaking change
> bump version

- nri-log-explorer/src/Main.hs
Paired with @stoeffel and @michaelglass
> Only read recent log

- nri-log-explorer/src/Main.hs
I was trying some stuff with io-streams (which didn't work out), but at least it produced this small cleanup.
> Small cleanup of AddRootSpan

- nri-env-parser/nri-env-parser.cabal
- nri-env-parser/package.yaml
- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-observability/nri-observability.cabal
- nri-observability/package.yaml
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
- nri-redis/nri-redis.cabal
- nri-redis/package.yaml
- nri-test-encoding/nri-test-encoding.cabal
- nri-test-encoding/package.yaml
right now readmes in stackage point to root repo
> publish package-specific homepage to stackage/hackage

- .envrc
- nix/mk-shell.nix
the readme references cachix. This adds / automates its usage
> add cachix

- nri-log-explorer/nri-log-explorer.cabal
- nri-log-explorer/package.yaml
- nri-observability/CHANGELOG.md
- nri-observability/nri-observability.cabal
- nri-observability/package.yaml
- nri-prelude/CHANGELOG.md
- nri-prelude/nri-prelude.cabal
- nri-prelude/package.yaml
> Update packages to support time-0.12
